ARG BUILD_FROM
FROM $BUILD_FROM

# System dependencies
RUN apk add --no-cache python3 py3-pip

# App
WORKDIR /app
COPY src/ /app/
COPY requirements.txt /app/

RUN pip3 install --no-cache-dir -r /app/requirements.txt

# Add-on entrypoint
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
